version: "3.9"

services:
  monitor_api:
    build: .
    container_name: monitor_api
    ports:
      - "5000:5000"

  monitor_worker:
    build: .
    container_name: monitor_worker
    entrypoint: ["sh", "-c", "echo START && ls -R /app && python3 /app/architecture/output_layer_monitor_worker.py"]
    depends_on:
      - monitor_api